trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo "Building the project..."
  displayName: 'Build'
- script: echo "Creating container image..."
  displayName: 'Build Container Image'
- script: echo "Running tests..."
  displayName: 'Test'
- script: echo "Deploying the application..."
  displayName: 'Deploy' 