trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    echo "Installing Python 3.8"
    sudo apt-get update
    sudo apt-get install python3 -y 
    python3 --version
    python3 helloworld.py  
  displayName: 'Run Python Script' 
