trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo "Building the project..."
  displayName: 'Build'
- script: echo "Creating container image..."
  displayName: 'Build Container Image'
- script: echo "Running tests..."
  displayName: 'Test'
- script: echo "Deploying the application..."
  displayName: 'Deploy' 
- script: | 
    echo "Running post-deployment tests..."
    mkdir -p test-results
    echo "Test results" > test-results/results.txt
    git --version 
    echo "checked git version"
    docker --version
    echo "checked docker version"
    terraform --version
    sudo apt-get install -y terraform
    echo "checked terraform version"
  displayName: 'Post-Deployment Tests'  